---

# vim: ts=2:sw=2:et:ft=yaml
# -*- mode: yaml; indent-tabs-mode: nil; tab-width: 2 -*-
# code: language=yaml insertSpaces=true tabSize=2

- name: APT | Add Docker apt repo key
  become: yes
  apt_key:
    keyserver: "{{ key_server }}"
    # http://keyserver.ubuntu.com/pks/lookup?search=docker&op=vindex
    id: "{{ docker_apt_repo_key_fingerprint }}"
    state: present

- name: APT | Force update of package lists
  become: yes
  apt:
    update_cache: yes
    #cache_valid_time: 3600

- name: Install base distro packages
  become: yes
  package:
    name: "{{ base_packages }}"
    state: present

# Add specified repository into sources list using specified filename.
- name: APT | Add Docker Community Edition repo
  become: yes
  apt_repository:
    repo: "{{ docker_apt_repo }}"
    update_cache: yes
    state: present
    # .list extension will be automatically added
    filename: "docker-ce"

- name: Install Docker related distro packages
  become: yes
  package:
    name: "{{ docker_related_distro_packages }}"
    state: present

- name: Start Docker daemon, enable starting at boot
  become: yes
  service:
    name: docker
    state: started
    enabled: yes

- name: Install Docker related Python modules
  pip:
    name: "{{ docker_related_python_modules }}"

...
